name: Backend

on:
  push:
    branches: [main]
    paths:
      - 'backend/**'
      - 'infra/**'
      - '.github/workflows/backend.yml'
  pull_request:
    paths:
      - 'backend/**'
      - 'infra/**'
      - '.github/workflows/backend.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Hello
        run: echo "Workflow ran successfully"